import { useCallback, useRef, useState } from 'react';

/**
 * Turns a submit handler into one that cannot run twice for the same intent
 * (planning-pms-verification.md, F-5 point 4; brainstorm E-43, E-46, REC-17).
 *
 * **Two guards, because one is not enough.**
 *
 * 1. *In the browser* — a ref, checked and set synchronously. `disabled={isSubmitting}` alone does
 *    not close the window: React state updates are asynchronous, so two clicks inside one render
 *    pass both see `isSubmitting === false` and both fire. A ref is written before the first
 *    `await` and is therefore already true when the second click arrives.
 * 2. *On the server* — a `submissionId` that travels with the request. The ref dies with the tab.
 *    A refresh mid-request, a retry after a timeout, or a second tab all defeat it, and at that
 *    point only the server can tell that two requests mean one registration. The same token is
 *    re-sent on every retry of the same form, which is what makes the create idempotent rather
 *    than merely rate-limited.
 *
 * The token is regenerated by {@link SubmitOnce.reset}, which the caller invokes when the form
 * genuinely starts a *new* intent — after a successful save that clears the form, for instance.
 * Without that, registering a second patient without a reload would replay the first token and be
 * answered with the first patient.
 */
export interface SubmitOnce {
  /**
   * Identifies this attempt. Send it with the request; re-send the same value on a retry.
   */
  submissionId: string;

  /** True while a submission is in flight. Drives the button's `disabled` and its label. */
  isSubmitting: boolean;

  /**
   * Runs `action` unless one is already running, in which case it does nothing and returns
   * `undefined` — the second click of a double-click is simply not an event.
   */
  submit: <T>(action: (submissionId: string) => Promise<T>) => Promise<T | undefined>;

  /** Issues a fresh token, so the next submit is a new intent rather than a replay. */
  reset: () => void;
}

function newToken(): string {
  // crypto.randomUUID is available in every browser this application targets and in jsdom under
  // Node 19+. The fallback is not security-sensitive - this value only has to be unique, and it
  // keeps the hook usable in an older test environment rather than throwing at import time.
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }

  return `${Date.now().toString(16)}-${Math.random().toString(16).slice(2)}`;
}

export function useSubmitOnce(): SubmitOnce {
  const [submissionId, setSubmissionId] = useState<string>(newToken);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // The synchronous half of guard 1. `isSubmitting` is for rendering; this is for deciding.
  const inFlight = useRef(false);

  const submit = useCallback(
    async <T,>(action: (submissionId: string) => Promise<T>): Promise<T | undefined> => {
      if (inFlight.current) {
        return undefined;
      }

      inFlight.current = true;
      setIsSubmitting(true);

      try {
        return await action(submissionId);
      } finally {
        // Always cleared, including when `action` throws. A failed save has to be retryable - a
        // form that locks itself after one network error is a form the physician has to reload,
        // and reloading is how typed work gets lost (E-47).
        inFlight.current = false;
        setIsSubmitting(false);
      }
    },
    [submissionId],
  );

  const reset = useCallback(() => {
    setSubmissionId(newToken());
  }, []);

  return { submissionId, isSubmitting, submit, reset };
}
