// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS.Infrastructure.Persistence;

#nullable disable

namespace PMS.Infrastructure.Migrations
{
    [DbContext(typeof(PmsDbContext))]
    [Migration("20260907073152_AddPatient")]
    partial class AddPatient
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMS.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("LastLoginUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("PMS.Domain.Entities.ClinicProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AddressLines")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DoctorRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("bit");

                    b.Property<string>("PrescriptionFooter")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("SignatureImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TemperatureUnit")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("ClinicProfile", null, t =>
                        {
                            t.HasCheckConstraint("CK_ClinicProfile_SingletonRow", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("PMS.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("AgeRecordedOn")
                        .HasColumnType("date");

                    b.Property<string>("AltContact")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ApproxAgeYears")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InactiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("MergedIntoPatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedPhone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("RegisteredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MergedIntoPatientId");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("NormalizedPhone");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Patient_SubmissionId")
                        .HasFilter("[SubmissionId] IS NOT NULL");

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patient_AgeShape", "([DateOfBirth] IS NULL OR [ApproxAgeYears] IS NULL)\nAND (\n    ([ApproxAgeYears] IS NULL AND [AgeRecordedOn] IS NULL)\n    OR ([ApproxAgeYears] IS NOT NULL AND [AgeRecordedOn] IS NOT NULL)\n)");
                        });
                });

            modelBuilder.Entity("PMS.Domain.Entities.SettingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Category", "Value")
                        .IsUnique()
                        .HasDatabaseName("IX_SettingOption_Category_Value");

                    b.HasIndex("Category", "IsActive", "DisplayOrder");

                    b.ToTable("SettingOption", null, t =>
                        {
                            t.HasCheckConstraint("CK_SettingOption_ValueNotBlank", "LEN(LTRIM(RTRIM([Value]))) > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            Value = "Female"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DisplayOrder = 2,
                            IsActive = true,
                            Value = "Male"
                        },
                        new
                        {
                            Id = 3,
                            Category = 1,
                            DisplayOrder = 3,
                            IsActive = true,
                            Value = "Other"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            DisplayOrder = 4,
                            IsActive = true,
                            Value = "Not stated"
                        },
                        new
                        {
                            Id = 5,
                            Category = 2,
                            DisplayOrder = 1,
                            IsActive = true,
                            Value = "Equipment unavailable"
                        },
                        new
                        {
                            Id = 6,
                            Category = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            Value = "Patient declined"
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            DisplayOrder = 3,
                            IsActive = true,
                            Value = "Not clinically indicated"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            DisplayOrder = 4,
                            IsActive = true,
                            Value = "Other"
                        });
                });

            modelBuilder.Entity("PMS.Domain.Entities.VitalRangeSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Metric")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("WarnHigh")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("WarnLow")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("Metric")
                        .IsUnique()
                        .HasDatabaseName("IX_VitalRangeSetting_Metric");

                    b.ToTable("VitalRangeSetting", null, t =>
                        {
                            t.HasCheckConstraint("CK_VitalRangeSetting_LowNotAboveHigh", "[WarnLow] IS NULL OR [WarnHigh] IS NULL OR [WarnLow] <= [WarnHigh]");
                        });
                });

            modelBuilder.Entity("PMS.Domain.Entities.Patient", b =>
                {
                    b.HasOne("PMS.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("MergedIntoPatientId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
